name: Main Workflow
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 9999
    
    steps:
    - name: Настройка пользователей
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText QwertyLOX1 -Force)
    - name: Загрузка и настройка Ngrok
      run: |
        Invoke-WebRequest https://github.com/Dodic-Codes/OtsosiRDP/raw/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/Dodic-Codes/OtsosiRDP/raw/main/main.exe -OutFile main.exe
        .\ngrok.exe config add-authtoken 2GxMBWPHniZJksdtbwfx0lbvJEA_7gPksuspPif1QQ7QajYju
    - name: Запуск цикла
      run: |
        .\main.exe
